# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

env:
  - TOXENV=py27
  - TOXENV=py34

# command to install dependencies
install:
  - pip install -U tox codecov

# command to run tests, e.g. python setup.py test
script: tox

after_success:
  - codecov

# config to deploy in PyPI when a tag is pushed
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: QNG/LK/USPuTBmeQ7tlrv/8U+n36NXigd+kThfaAs6SZ8JDMscA9Es2wJ++frv5vTMcpUHoN3wqdNZrIaJx71wltN51l7HHHQwbggfEKtFvqaX3GPShJFy9RerAyoulPCRYAJOirts4zAzCNMnqDvpeUB1JLlp8e91pHl8ZYZqtX7C0s5MXbbldHx8ZOOw4SG26DOjgHGs+yZG8gMvrF86NwxxjVbgQ/ExUH2B2Ajy00ZLmhLqnXtm6YEVcRpoyVhAEt81/LmLbkfZfZV6jLljg1IFVz1zAeQO2Gu27vjK1rbf5gq9uZsPeo1/2I3fo9sp0Xwy++3GPoOVcODo8m4FjpLk/soo8cy+ljqq61/xRESFuUWz6LF44o5WkbuqFO3pj1hKJj1NoAmWAHeG1OY/jTzV8C9VLfbcYkxD0Emrti7XYsV8T8PIkzi6PTs9ufFvFHzWVhtpvMrdF2W3hLhYJESS7pSB/LvM7ajSw8rbFz1MXOzUjPEiRq3GMI2y3NuM2Ngoy1iXOQRYk0V9u0KUQe/3/fHqVINgHDTCu/IOEvmQStgyyrvgU0ehqJDXAfwRtv41uvQXzoV83tel+VS7vOiPBygds3bNfi+pFPnYW9DTO/Y+MqBwF6SvpN4GONMNS/qRkgSa1inyjnkRswOfpsh41DXCR25xpTqdy0PJg=
  on:
    tags: true
    repo: scrapinghub/extruct
    condition: $TOXENV == py27
