# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    #- python: 3.4
      #env: TOXENV=py34
    #- python: 3.5
      #env: TOXENV=py35
    #- python: 3.6
      #env: TOXENV=py36
    - python: 3.5
      env: TOXENV=pypy3

# command to install dependencies
install:
  - |
      if [ "$TOXENV" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        # get latest PyPy from pyenv directly (thanks to natural version sort option -V)
        export PYPY_VERSION=`"$PYENV_ROOT/bin/pyenv" install --list |grep -o -E 'pypy-[0-9][\.0-9]*$' |sort -V |tail -1`
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/$PYPY_VERSION/bin/python" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
  - |
      if [ "$TOXENV" = "pypy3" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        # get latest PyPy3 from pyenv directly (thanks to natural version sort option -V)
        export PYPY3_VERSION=`"$PYENV_ROOT/bin/pyenv" install --list |grep -o -E 'pypy3[\.0-9]*-[0-9][\.0-9]*(-alpha[0-9]*)?$' |sort -V |tail -1`
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "$PYPY3_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/$PYPY3_VERSION/bin/python" "$HOME/virtualenvs/$PYPY3_VERSION"
        source "$HOME/virtualenvs/$PYPY3_VERSION/bin/activate"
      fi
  - pip install -U tox codecov

# command to run tests, e.g. python setup.py test
script: tox

after_success:
  - codecov

# config to deploy in PyPI when a tag is pushed
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: QNG/LK/USPuTBmeQ7tlrv/8U+n36NXigd+kThfaAs6SZ8JDMscA9Es2wJ++frv5vTMcpUHoN3wqdNZrIaJx71wltN51l7HHHQwbggfEKtFvqaX3GPShJFy9RerAyoulPCRYAJOirts4zAzCNMnqDvpeUB1JLlp8e91pHl8ZYZqtX7C0s5MXbbldHx8ZOOw4SG26DOjgHGs+yZG8gMvrF86NwxxjVbgQ/ExUH2B2Ajy00ZLmhLqnXtm6YEVcRpoyVhAEt81/LmLbkfZfZV6jLljg1IFVz1zAeQO2Gu27vjK1rbf5gq9uZsPeo1/2I3fo9sp0Xwy++3GPoOVcODo8m4FjpLk/soo8cy+ljqq61/xRESFuUWz6LF44o5WkbuqFO3pj1hKJj1NoAmWAHeG1OY/jTzV8C9VLfbcYkxD0Emrti7XYsV8T8PIkzi6PTs9ufFvFHzWVhtpvMrdF2W3hLhYJESS7pSB/LvM7ajSw8rbFz1MXOzUjPEiRq3GMI2y3NuM2Ngoy1iXOQRYk0V9u0KUQe/3/fHqVINgHDTCu/IOEvmQStgyyrvgU0ehqJDXAfwRtv41uvQXzoV83tel+VS7vOiPBygds3bNfi+pFPnYW9DTO/Y+MqBwF6SvpN4GONMNS/qRkgSa1inyjnkRswOfpsh41DXCR25xpTqdy0PJg=
  on:
    tags: true
    repo: scrapinghub/extruct
    condition: $TOXENV == py27
