[tox]
requires =
    tox-uv
envlist =
    pre-commit
    twinecheck
    py3{10-15}
min_version = 4.25.0

[testenv]
deps =
    pytest
    pytest-cov
extras =
    cli
passenv =
    PYTEST_ADDOPTS
commands =
    pytest {posargs:--cov=extruct --cov-report= --cov-report=term-missing --cov-report=xml tests}

[testenv:pre-commit]
deps =
    pre-commit
skip_install = true
commands =
    pre-commit run {posargs:--all-files --show-diff-on-failure}

[testenv:twinecheck]
basepython = python3
deps =
    twine==7.0.0
    build==1.5.0
commands =
    python -m build --sdist
    twine check dist/*
